CREATE TABLE careers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  career_name VARCHAR(255) NOT NULL,
  career_code VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
